Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "manager"
  config.vm.network "private_network", ip: "192.168.56.2"
  # config.vm.provision "shell", path: "provision.sh"
  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
  end

end
