---
- name: configure app server
  hosts: app01
  user: vagrant
  become: yes

  vars:
    dbhost: "db01"
    dbname: "notes"
    dbusername: "notesapp"
    dbpassword: "123456"
    
  tasks:
    - name: add app user
      user:
        name: app
        comment: app user
        uid: 500

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Run apt-get update with fix-missing
      command: apt-get update --fix-missing
      become: yes

    - name: java install
      apt:
        name: openjdk-8-jdk
        state: latest

    - name: install maven
      apt:
        name: maven
        state: latest

    - name: create app directory
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app

    - name: git client install
      apt:
        name: git
        state: latest

    - name: Configure Git to trust the directory
      command: git config --global --add safe.directory /opt/notes
      become: yes

    - name: git clone repository
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes

    - name: config properties for db layer
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties

    - name: generate app packages
      command: mvn -f /opt/notes/pom.xml package
      # become: yes
      # become_user: app

    - name: register package version
      shell: 
        cmd: mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: /opt/notes/
      register: app_version

    - name: config systemd service
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
      notify: reload daemon

    - name: start notes service
      service:
        name: notes
        state: restarted

  roles:
    - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes