---
- name: Config db server
  hosts: db01

  user: vagrant
  become: yes

  vars_files: 
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "123456"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql